//! Runtime theme, published by the nix theme layer.
//!
//! `home/themes/lib/era.nix` writes the resolved palette to
//! `$XDG_CONFIG_HOME/theme/current.toml` whenever a host switches era or
//! variant. Reading it here means the toolkit follows the desktop
//! instead of carrying a second, hand-maintained copy of the palette --
//! which is exactly how `colors.rs` and `home/themes/neomil/palettes.nix`
//! came to hold transcriptions of each other.
//!
//! `colors.rs` stays the fallback, so the crate still runs standalone
//! with no nix in sight.
//!
//! The parser is deliberately dependency-free. The file is generated by
//! us in a fixed shape, so pulling in serde and a TOML implementation to
//! read seven key/value pairs is not worth the build weight. It handles
//! exactly what the generator emits: `# comments`, `[sections]`, and
//! `key = "value"`.

use std::collections::HashMap;

/// A colour as published by the theme layer: eight-bit sRGB, no alpha.
/// Kept free of any `iced` types so the parser can be tested without
/// building the toolkit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

impl Rgb {
    /// Parse `#rrggbb`. Returns `None` on anything else, including the
    /// three-digit short form, which the generator never emits.
    pub fn parse(s: &str) -> Option<Self> {
        let hex = s.strip_prefix('#')?;
        if hex.len() != 6 || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            return None;
        }
        Some(Rgb {
            r: u8::from_str_radix(&hex[0..2], 16).ok()?,
            g: u8::from_str_radix(&hex[2..4], 16).ok()?,
            b: u8::from_str_radix(&hex[4..6], 16).ok()?,
        })
    }
}

/// Whether the palette runs dark-on-light or light-on-dark. The theme
/// layer infers this from the background's luma rather than making each
/// palette declare it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Polarity {
    Dark,
    Light,
}

/// The seven semantic roles every generated era speaks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Roles {
    pub bg: Rgb,
    pub panel: Rgb,
    pub border: Rgb,
    pub dim: Rgb,
    pub fg: Rgb,
    pub alert: Rgb,
    /// Improvised label accent. Falls back to `fg` in the theme layer,
    /// so it is always present here.
    pub tape: Rgb,
}

#[derive(Debug, Clone)]
pub struct Theme {
    pub era: String,
    pub variant: String,
    pub polarity: Polarity,
    pub ui_font: String,
    pub colors: Roles,
}

impl Theme {
    /// Load the published theme, falling back to the compiled palette if
    /// the file is missing or unreadable. Never fails: a toolkit that
    /// refuses to start because a theme file is absent is worse than one
    /// that uses its own defaults.
    pub fn load() -> Self {
        Self::path()
            .and_then(|p| std::fs::read_to_string(p).ok())
            .and_then(|s| Self::parse(&s))
            .unwrap_or_else(Self::fallback)
    }

    /// `$XDG_CONFIG_HOME/theme/current.toml`, or the usual default.
    pub fn path() -> Option<std::path::PathBuf> {
        let base = std::env::var_os("XDG_CONFIG_HOME")
            .map(std::path::PathBuf::from)
            .or_else(|| {
                std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".config"))
            })?;
        Some(base.join("theme").join("current.toml"))
    }

    pub fn parse(src: &str) -> Option<Self> {
        let flat = parse_flat(src);

        let role = |name: &str| -> Option<Rgb> {
            flat.get(&format!("colors.{name}"))
                .and_then(|v| Rgb::parse(v))
        };

        Some(Theme {
            era: flat.get("era").cloned().unwrap_or_default(),
            variant: flat.get("variant").cloned().unwrap_or_default(),
            polarity: match flat.get("polarity").map(String::as_str) {
                Some("light") => Polarity::Light,
                _ => Polarity::Dark,
            },
            ui_font: flat
                .get("font.ui")
                .cloned()
                .unwrap_or_else(|| "Rajdhani".to_string()),
            colors: Roles {
                bg: role("bg")?,
                panel: role("panel")?,
                border: role("border")?,
                dim: role("dim")?,
                fg: role("fg")?,
                alert: role("alert")?,
                tape: role("tape")?,
            },
        })
    }

    /// The sampled reference palette from `colors.rs`, for when nothing
    /// has been published.
    fn fallback() -> Self {
        Theme {
            era: "neomil".into(),
            variant: "reference".into(),
            polarity: Polarity::Dark,
            ui_font: "Rajdhani".into(),
            colors: Roles {
                bg: Rgb { r: 5, g: 3, b: 4 },
                panel: Rgb { r: 0, g: 26, b: 51 },
                border: Rgb { r: 94, g: 17, b: 18 },
                dim: Rgb { r: 163, g: 34, b: 38 },
                fg: Rgb { r: 222, g: 46, b: 46 },
                alert: Rgb { r: 255, g: 59, b: 69 },
                tape: Rgb { r: 222, g: 222, b: 222 },
            },
        }
    }
}

/// Flatten `[section]` + `key = "value"` into `section.key -> value`.
fn parse_flat(src: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();
    let mut section = String::new();

    for raw in src.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            section = name.trim().to_string();
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            continue;
        };

        let key = key.trim();
        let value = value.trim().trim_matches('"');

        let full = if section.is_empty() {
            key.to_string()
        } else {
            format!("{section}.{key}")
        };
        out.insert(full, value.to_string());
    }

    out
}

impl From<Rgb> for iced::Color {
    fn from(c: Rgb) -> Self {
        iced::Color::from_rgb8(c.r, c.g, c.b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // r##: the content contains `"#` (every colour literal), which would
    // terminate an r#"..."# raw string early.
    const SAMPLE: &str = r##"
# Generated from home/themes/neomil roles. No literals here.
era = "neomil"
variant = "bleach"
polarity = "light"

[font]
ui = "Rajdhani"

[colors]
bg = "#e9e7e3"
panel = "#dcd9d3"
border = "#b3ada4"
dim = "#6e6960"
fg = "#1a1917"
alert = "#c0201f"
tape = "#b02226"
"##;

    #[test]
    fn parses_generated_file() {
        let t = Theme::parse(SAMPLE).expect("sample should parse");
        assert_eq!(t.era, "neomil");
        assert_eq!(t.variant, "bleach");
        assert_eq!(t.polarity, Polarity::Light);
        assert_eq!(t.ui_font, "Rajdhani");
        assert_eq!(t.colors.bg, Rgb { r: 233, g: 231, b: 227 });
        assert_eq!(t.colors.tape, Rgb { r: 176, g: 34, b: 38 });
    }

    #[test]
    fn missing_role_is_rejected_rather_than_defaulted() {
        // A half-written file should fall back wholesale, not silently
        // mix a published background with a compiled foreground.
        let truncated = "era = \"x\"\n[colors]\nbg = \"#000000\"\n";
        assert!(Theme::parse(truncated).is_none());
    }

    #[test]
    fn rejects_malformed_colours() {
        assert!(Rgb::parse("#fff").is_none());
        assert!(Rgb::parse("e9e7e3").is_none());
        assert!(Rgb::parse("#gggggg").is_none());
        assert_eq!(Rgb::parse("#010203"), Some(Rgb { r: 1, g: 2, b: 3 }));
    }
}
