#!/usr/bin/env bash

WALLPAPERS_DIR="$HOME/.config/hypr/walls"
STYLE="$HOME/.config/rofi/scripts/wallpaper/style.rasi"

# Pick a wallpaper via rofi
choice=$(
	ls --escape "$WALLPAPERS_DIR" |
		while read -r A; do
		echo -en "$A\x00icon\x1f$WALLPAPERS_DIR/$A\n"
		done |
	rofi -dmenu -i -show-icons -p "Wallpaper" -theme "$STYLE"
)

[ -z "$choice" ] && exit 0

wp="$WALLPAPERS_DIR/$choice"

killall hyprpaper
hyprpaper &

sleep 0.2
hyprctl hyprpaper wallpaper "DP-2,$wp"
hyprctl hyprpaper wallpaper "HDMI-A-1,$wp"
