//! Runtime theme, published by the nix theme layer.
//!
//! `home/themes/lib/era.nix` writes the resolved palette to
//! `$XDG_CONFIG_HOME/theme/current.toml` whenever a host switches era or
//! variant. Reading it here means the toolkit follows the desktop
//! instead of carrying a second, hand-maintained copy of the palette --
//! which is exactly how the crate's original `colors.rs` (deleted in
//! `61db2ae`) and `home/themes/neomil/palettes.nix` came to hold
//! transcriptions of each other.
//!
//! `Theme::fallback` keeps the neomil reference palette inline, so
//! the crate still runs standalone with no nix in sight.
//!
//! The parser is deliberately dependency-free. The file is generated by
//! us in a fixed shape, so pulling in serde and a TOML implementation to
//! read a dozen key/value pairs is not worth the build weight. It
//! handles exactly what the generator emits: `# comments`,
//! `[sections]`, and `key = "value"`.
//!
//! The seven base roles are required; a file missing one is rejected
//! wholesale rather than half-applied. The ornamental roles a
//! maximalist era adds ([`ExtraRoles`]) are optional in the file, which
//! is what lets the vocabulary grow without invalidating a theme file
//! written before it did.

use std::collections::HashMap;

/// A colour as published by the theme layer: eight-bit sRGB, no alpha.
/// Kept free of any `iced` types so the parser can be tested without
/// building the toolkit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

impl Rgb {
    /// Parse `#rrggbb`. Returns `None` on anything else, including the
    /// three-digit short form, which the generator never emits.
    pub fn parse(s: &str) -> Option<Self> {
        let hex = s.strip_prefix('#')?;
        if hex.len() != 6 || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            return None;
        }
        Some(Rgb {
            r: u8::from_str_radix(&hex[0..2], 16).ok()?,
            g: u8::from_str_radix(&hex[2..4], 16).ok()?,
            b: u8::from_str_radix(&hex[4..6], 16).ok()?,
        })
    }
}

/// Whether the palette runs dark-on-light or light-on-dark. The theme
/// layer infers this from the background's luma rather than making each
/// palette declare it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Polarity {
    Dark,
    Light,
}

/// The seven semantic roles every generated era speaks, plus whatever
/// optional ones it declared.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Roles {
    pub bg: Rgb,
    pub panel: Rgb,
    pub border: Rgb,
    pub dim: Rgb,
    pub fg: Rgb,
    pub alert: Rgb,
    /// Improvised label accent. Falls back to `fg` in the theme layer,
    /// so it is always present here.
    pub tape: Rgb,
    /// What a maximalist era publishes on top. Empty for entropism and
    /// neomil, and empty for any file written before the vocabulary
    /// existed -- a missing key is not an error.
    pub extra: ExtraRoles,
}

/// The optional half of the vocabulary (`extraNames` in
/// `home/themes/lib/roles.nix`).
///
/// Every field is `None` unless the published theme names it. That is
/// the whole contract: kitsch declares no `inset` because its cards are
/// unfilled outlines, neokitsch declares no `emphasis` because it has
/// no highlight band, and the minimalist eras declare none of it. A
/// reader falls back rather than assuming presence -- see
/// [`crate::palette::Palette`]'s accessors for the fallbacks the
/// toolkit uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ExtraRoles {
    /// Notched accent band: kitsch's shelf band, neokitsch's footer
    /// nameplate.
    pub banner: Option<Rgb>,
    /// Text and line-work drawn on `banner`.
    pub on_banner: Option<Rgb>,
    /// Highlight band behind key figures: kitsch's mint stat bar.
    pub emphasis: Option<Rgb>,
    /// Figures sitting on `emphasis`.
    pub on_emphasis: Option<Rgb>,
    /// Lit edge or face of a raised surface.
    pub bevel: Option<Rgb>,
    /// Its receding, shaded edge.
    pub shade: Option<Rgb>,
    /// Solid non-structural decoration: kitsch's page-curl, neokitsch's
    /// strata wedge.
    pub ornament: Option<Rgb>,
    /// Recessed fill: neokitsch's login field and socket wells.
    pub inset: Option<Rgb>,
}

#[derive(Debug, Clone)]
pub struct Theme {
    pub era: String,
    pub variant: String,
    pub polarity: Polarity,
    pub ui_font: String,
    pub colors: Roles,
}

impl Theme {
    /// Load the published theme, falling back to the compiled palette if
    /// the file is missing or unreadable. Never fails: a toolkit that
    /// refuses to start because a theme file is absent is worse than one
    /// that uses its own defaults.
    pub fn load() -> Self {
        Self::path()
            .and_then(|p| std::fs::read_to_string(p).ok())
            .and_then(|s| Self::parse(&s))
            .unwrap_or_else(Self::fallback)
    }

    /// `$XDG_CONFIG_HOME/theme/current.toml`, or the usual default.
    pub fn path() -> Option<std::path::PathBuf> {
        let base = std::env::var_os("XDG_CONFIG_HOME")
            .map(std::path::PathBuf::from)
            .or_else(|| {
                std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".config"))
            })?;
        Some(base.join("theme").join("current.toml"))
    }

    pub fn parse(src: &str) -> Option<Self> {
        let flat = parse_flat(src);

        let role = |name: &str| -> Option<Rgb> {
            flat.get(&format!("colors.{name}"))
                .and_then(|v| Rgb::parse(v))
        };

        Some(Theme {
            era: flat.get("era").cloned().unwrap_or_default(),
            variant: flat.get("variant").cloned().unwrap_or_default(),
            polarity: match flat.get("polarity").map(String::as_str) {
                Some("light") => Polarity::Light,
                _ => Polarity::Dark,
            },
            ui_font: flat
                .get("font.ui")
                .cloned()
                .unwrap_or_else(|| "Rajdhani".to_string()),
            colors: Roles {
                bg: role("bg")?,
                panel: role("panel")?,
                border: role("border")?,
                dim: role("dim")?,
                fg: role("fg")?,
                alert: role("alert")?,
                tape: role("tape")?,
                // No `?` past this line. The seven are required -- a
                // half-written file should fall back wholesale rather
                // than mix palettes -- but an absent optional role is
                // the normal case, not a truncated file.
                extra: ExtraRoles {
                    banner: role("banner"),
                    on_banner: role("onBanner"),
                    emphasis: role("emphasis"),
                    on_emphasis: role("onEmphasis"),
                    bevel: role("bevel"),
                    shade: role("shade"),
                    ornament: role("ornament"),
                    inset: role("inset"),
                },
            },
        })
    }

    /// The sampled neomil reference palette (once `colors.rs`, now also
    /// the era table in `eras::neomil`), for when nothing has been
    /// published.
    fn fallback() -> Self {
        Theme {
            era: "neomil".into(),
            variant: "reference".into(),
            polarity: Polarity::Dark,
            ui_font: "Rajdhani".into(),
            colors: Roles {
                bg: Rgb { r: 5, g: 3, b: 4 },
                panel: Rgb { r: 0, g: 26, b: 51 },
                border: Rgb { r: 94, g: 17, b: 18 },
                dim: Rgb { r: 163, g: 34, b: 38 },
                fg: Rgb { r: 222, g: 46, b: 46 },
                alert: Rgb { r: 255, g: 59, b: 69 },
                tape: Rgb { r: 222, g: 222, b: 222 },
                // Neomil is minimalist and declares none of the
                // ornamental roles, which is also what the crate's own
                // fallback should say: leave them to the era table.
                extra: ExtraRoles::default(),
            },
        }
    }
}

/// Flatten `[section]` + `key = "value"` into `section.key -> value`.
fn parse_flat(src: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();
    let mut section = String::new();

    for raw in src.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            section = name.trim().to_string();
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            continue;
        };

        let key = key.trim();
        let value = value.trim().trim_matches('"');

        let full = if section.is_empty() {
            key.to_string()
        } else {
            format!("{section}.{key}")
        };
        out.insert(full, value.to_string());
    }

    out
}

impl From<Rgb> for iced::Color {
    fn from(c: Rgb) -> Self {
        iced::Color::from_rgb8(c.r, c.g, c.b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // r##: the content contains `"#` (every colour literal), which would
    // terminate an r#"..."# raw string early.
    const SAMPLE: &str = r##"
# Generated from home/themes/neomil roles. No literals here.
era = "neomil"
variant = "bleach"
polarity = "light"

[font]
ui = "Rajdhani"

[colors]
bg = "#e9e7e3"
panel = "#dcd9d3"
border = "#b3ada4"
dim = "#6e6960"
fg = "#1a1917"
alert = "#c0201f"
tape = "#b02226"
"##;

    #[test]
    fn parses_generated_file() {
        let t = Theme::parse(SAMPLE).expect("sample should parse");
        assert_eq!(t.era, "neomil");
        assert_eq!(t.variant, "bleach");
        assert_eq!(t.polarity, Polarity::Light);
        assert_eq!(t.ui_font, "Rajdhani");
        assert_eq!(t.colors.bg, Rgb { r: 233, g: 231, b: 227 });
        assert_eq!(t.colors.tape, Rgb { r: 176, g: 34, b: 38 });
        // A minimalist era publishes the seven and nothing else, and
        // the parser must not invent the rest.
        assert_eq!(t.colors.extra, ExtraRoles::default());
    }

    // The tail lib/era.nix appends for kitsch, verbatim.
    const KITSCH_EXTRAS: &str = r##"
era = "kitsch"
variant = "reference"
polarity = "dark"

[colors]
bg = "#0b0b07"
panel = "#1c0f16"
border = "#5fd6c2"
dim = "#4d9484"
fg = "#7ddec8"
alert = "#fcc428"
tape = "#f08c1e"
banner = "#fcc428"
onBanner = "#37220f"
emphasis = "#87f4d9"
onEmphasis = "#0b3b31"
bevel = "#2bc4ac"
shade = "#177a6b"
ornament = "#1cb39b"
"##;

    #[test]
    fn parses_optional_roles_and_leaves_undeclared_ones_none() {
        let t = Theme::parse(KITSCH_EXTRAS).expect("sample should parse");
        let x = t.colors.extra;
        assert_eq!(x.banner, Rgb::parse("#fcc428"));
        assert_eq!(x.on_banner, Rgb::parse("#37220f"));
        assert_eq!(x.emphasis, Rgb::parse("#87f4d9"));
        assert_eq!(x.on_emphasis, Rgb::parse("#0b3b31"));
        assert_eq!(x.bevel, Rgb::parse("#2bc4ac"));
        assert_eq!(x.shade, Rgb::parse("#177a6b"));
        assert_eq!(x.ornament, Rgb::parse("#1cb39b"));
        // Kitsch has no well anywhere in its references, so it declares
        // no `inset` -- absence has to survive the round trip.
        assert_eq!(x.inset, None);
    }

    #[test]
    fn missing_role_is_rejected_rather_than_defaulted() {
        // A half-written file should fall back wholesale, not silently
        // mix a published background with a compiled foreground.
        let truncated = "era = \"x\"\n[colors]\nbg = \"#000000\"\n";
        assert!(Theme::parse(truncated).is_none());
    }

    #[test]
    fn rejects_malformed_colours() {
        assert!(Rgb::parse("#fff").is_none());
        assert!(Rgb::parse("e9e7e3").is_none());
        assert!(Rgb::parse("#gggggg").is_none());
        assert_eq!(Rgb::parse("#010203"), Some(Rgb { r: 1, g: 2, b: 3 }));
    }
}
